apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-06T18:26:22Z"
  labels:
    app: streams-client-webapp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-06-06T18:26:22Z"
  name: streams-client-webapp-service
  namespace: default
  resourceVersion: "11388"
  selfLink: /api/v1/namespaces/default/services/streams-client-webapp-service
  uid: e6487f32-b09f-4f89-9c17-977165e830a8
spec:
  clusterIP: 10.111.65.31
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30446
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: streams-client-webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
